name: code-cov

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      # copy code to machine
      - uses: actions/checkout@v4

      - name: install aws-cli
        run: |
          sudo apt install curl unzip -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      #  module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
      - name: fix issue
        run: |
          python3 -m pip install pip --upgrade
          pip install pyopenssl --upgrade
          
      # install deps
      - name: Set requirements
        run: pip install -r requirements.txt.cpu


      # removing dataset & old confusion-matrcies ğŸŒ€ğŸ˜¶â€ğŸŒ«ï¸
      - name: cleaning existing files ğŸª¥
        run: make trash
      
      # download dataset
      - name: download dataset from s3
        run: dvc pull
        
      # testing and push results to code-cov
      - name: running evaluation on already trained-model::Nov-09-2024-3:51AM
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true